name: CI/CD Pipeline

on:
  schedule:
    # Runs at 00:00 UTC daily
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

    - name: Run TestNG Tests
      run: mvn test

    - name: Deploy to server
      if: false  # This will prevent the deployment step from running
      uses: some/deployment-action@v1
      with:
        server-password: ${{ secrets.GITHUB_TOKEN }}
        distribution: 'placeholder-value'  # Placeholder value for `distribution`
        overwrite-settings: true
