name: CI/CD Pipeline

on:
  schedule:
    # Runs at 00:00 UTC daily
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Download TestNG jar
      run: curl -L -o testng.jar https://repo1.maven.org/maven2/org/testng/testng/7.4.0/testng-7.4.0.jar

    - name: Compile Java code
      run: javac -cp "testng.jar" src/test/java/TestNGRunner.java

    - name: Run TestNG tests
      run: java -cp ".:testng.jar" org.testng.TestNG src/test/java/TestNGRunner.java

    - name: Deploy to server
      if: false  # This will prevent the deployment step from running
      uses: some/deployment-action@v1
      with:
        server-password: ${{ secrets.GITHUB_TOKEN }}
        distribution: 'placeholder-value'  # Placeholder value for `distribution`
        overwrite-settings: true
