name: Run TestNG Tests

on:
  push:
    branches:
      - main  # Adjust based on the branch you want to trigger the workflow
  workflow_dispatch:
    # Enables manual triggering of the workflow
  schedule:
    # Runs every hour
    - cron: '0 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'  # Change as needed

    - name: Install dependencies
      run: |
        # Adjust based on your build tool
        # For Maven:
        mvn install
        # For Gradle:
        # gradle build

    - name: Execute TestNG Tests
      run: |
        # Using Maven to execute TestNG with the suite file
        mvn test -Dsurefire.suiteXmlFiles=testng.xml
